---
- name: Query subnets
  redhat.satellite.subnet_info:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: no
    search: "domain = home"
  register: subnet_info

- name: Show subnet info
  debug:
    var: subnet_info
